# Generated by Django 2.2.16 on 2022-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='DNI',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Materias_en_curso',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
