# Generated by Django 2.2.16 on 2022-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_auto_20220504_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Materias_en_curso',
            field=models.CharField(default='Ninguna', max_length=200),
        ),
    ]
